
global:
  namespace: nm-kubuculum
  base_directory: /root/mpillai/runs

run_control:
  benchmark: fio_random
  storageclass: ocs-storagecluster-ceph-rbd

benchmarks:
  fio_random:
    filesize_gb: 4
    numjobs: 2
    runtime_sec: 20

multirun_control:
  test_list:
    - benchmarks:
        fio_random:
          ninstances: 2
          bs_kb: 4
