
global:
  namespace: nm-kubuculum
  base_directory: /root/mpillai/runs

run_control:
  benchmark: fio_random
  storageclass: ocs-storagecluster-ceph-rbd

benchmarks:
  fio_random:
    filesize_gb: 1
    numjobs: 1
    runtime_sec: 10

multirun_control:
  test_list:
    - test_tag: bs-4
      benchmarks:
        fio_random:
          bs_kb: 4
